# Generated by Django 5.1.2 on 2024-10-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_author_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ImageField(blank=True, upload_to="bioImages/"),
        ),
    ]
