# Generated by Django 5.1.2 on 2024-11-27 18:36

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_author_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=django_bleach.models.BleachField(),
        ),
    ]
