# Generated by Django 5.1.2 on 2024-11-30 15:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_author_img_post_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="img",
            field=models.ImageField(
                default="author_images/default.svg",
                upload_to="author_images/",
                validators=[api.models.validate_image],
            ),
        ),
    ]
