# Generated by Django 5.1.2 on 2024-12-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
