# Generated by Django 5.2.4 on 2025-08-09 15:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img',
            field=cloudinary.models.CloudinaryField(default='author_images/default.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
