# Generated by Django 5.2.4 on 2025-08-09 17:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_author_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ddwinmcui/image/upload/v1754761518/avatar-default_juyaap.svg', max_length=255, verbose_name='image'),
        ),
    ]
